import React,{useEffect,useState} from "react";
import {api,qs} from "../lib/api";
import {Badge,Button,DataTable,Field,Modal,PageHeader} from "../components/ui";
import {useI18n} from "../lib/i18nContext";
const roles=["tenant_owner","group_admin","central_director","school_admin","branch_manager","academic_manager","finance_manager","hr_manager","admissions_manager","department_manager","teacher","staff","viewer"];
export default function AccessPage({tenantId,branchId,branches}:{tenantId:string,branchId:string|null,branches:any[]}){
 const {lang,label}=useI18n(),c=(en:string,ku:string,ar:string,tr:string)=>lang==="ku"?ku:lang==="ar"?ar:lang==="tr"?tr:en;
 const roleName=(r:string)=>({tenant_owner:c("Tenant Owner","خاوەنی کڕیار / گرووپ","مالك العميل / المجموعة","Müşteri / Grup Sahibi"),group_admin:c("Group Admin","بەڕێوەبەری گرووپ","مدير المجموعة","Grup Yöneticisi"),central_director:c("Central Director","بەڕێوەبەری ناوەندی","المدير المركزي","Merkez Direktörü"),school_admin:c("School Admin","بەڕێوەبەری قوتابخانە","مدير المدرسة","Okul Yöneticisi"),branch_manager:c("Branch Manager","بەڕێوەبەری لق","مدير الفرع","Şube Yöneticisi"),academic_manager:c("Academic Manager","بەڕێوەبەری ئەکادیمی","المدير الأكاديمي","Akademik Yönetici"),finance_manager:c("Finance Manager","بەڕێوەبەری دارایی","المدير المالي","Finans Yöneticisi"),hr_manager:c("HR Manager","بەڕێوەبەری سەرچاوە مرۆییەکان","مدير الموارد البشرية","İK Yöneticisi"),admissions_manager:c("Admissions Manager","بەڕێوەبەری وەرگرتن","مدير القبول","Kabul Yöneticisi"),department_manager:c("Department Manager","بەڕێوەبەری بەش","مدير القسم","Bölüm Yöneticisi"),teacher:c("Teacher","مامۆستا","معلم","Öğretmen"),staff:c("Staff","کارمەند","موظف","Personel"),viewer:c("Viewer","تەنها بینەر","مشاهد","Görüntüleyici")}[r]||label(r.replaceAll("_"," ")));
 const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<any>({name:"",email:"",password:"",role_code:"viewer",branch_id:branchId||"",can_delegate:false,preferred_language:"en"});
 const load=()=>api<any>("/api/users"+qs({tenant_id:tenantId,branch_id:branchId})).then(r=>setRows(r.rows));useEffect(()=>{load()},[tenantId,branchId]);
 async function create(e:React.FormEvent){e.preventDefault();try{await api("/api/users",{method:"POST",body:JSON.stringify({...form,tenant_id:tenantId,branch_id:form.branch_id||null})});setOpen(false);load()}catch(e:any){setError(e.message)}}
 return <div><PageHeader title={c("Users & Delegated Access","بەکارهێنەران و دەسەڵاتی سپێردراو","المستخدمون والصلاحيات المفوضة","Kullanıcılar ve Yetkilendirilmiş Erişim")} description={c("Role assignments carry tenant/branch scope and cannot escalate above the delegator.","دانانی ڕۆڵ بە ئاستی کڕیار/لقەوە بەستراوە و ناتوانێت لە دەسەڵاتی کەسی سپێرەر بەرزتر بێت.","تعيينات الأدوار مرتبطة بنطاق العميل/الفرع ولا يمكنها تجاوز صلاحية المفوِّض.","Rol atamaları müşteri/şube kapsamı taşır ve yetki veren kişinin seviyesinin üzerine çıkamaz.")} actions={<Button onClick={()=>setOpen(true)}>+ {c("Create user","دروستکردنی بەکارهێنەر","إنشاء مستخدم","Kullanıcı oluştur")}</Button>}/>
 <div className="panel"><DataTable rows={rows} columns={[
  {key:"name",label:c("User","بەکارهێنەر","المستخدم","Kullanıcı"),render:r=><div><strong>{r.name}</strong><small className="cell-sub">{r.email}</small></div>},
  {key:"assignments",label:c("Roles","ڕۆڵەکان","الأدوار","Roller"),render:r=><div className="chips">{(r.assignments||[]).map((a:any)=><Badge key={a.id} tone="info">{roleName(a.role_code)}{a.branch_id?` · ${c("branch","لق","فرع","şube")}`:""}</Badge>)}</div>},
  {key:"status",label:c("Status","دۆخ","الحالة","Durum"),render:r=><Badge tone="good">{label(r.status)}</Badge>},{key:"created_at",label:c("Created","دروستکراو","أُنشئ","Oluşturuldu"),render:r=>new Date(r.created_at).toLocaleDateString(lang==="ku"?"ku-Arab":lang)}
 ]}/></div>
 <Modal open={open} onClose={()=>setOpen(false)} title={c("Create scoped user","دروستکردنی بەکارهێنەری سنووردار","إنشاء مستخدم محدد النطاق","Kapsamlı kullanıcı oluştur")}>
 {error&&<div className="alert alert-error">{error}</div>}<form onSubmit={create} className="form-grid">
  <Field label={c("Full name","ناوی تەواو","الاسم الكامل","Ad Soyad")}><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label={c("Email","ئیمەیڵ","البريد الإلكتروني","E-posta")}><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field>
  <Field label={c("Temporary password","وشەی نهێنی کاتی","كلمة المرور المؤقتة","Geçici parola")} hint={c("Minimum 10 characters","لانیکەم ١٠ پیت","10 أحرف على الأقل","En az 10 karakter")}><input required minLength={10} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field>
  <Field label={c("Role","ڕۆڵ","الدور","Rol")}><select value={form.role_code} onChange={e=>setForm({...form,role_code:e.target.value})}>{roles.map(r=><option key={r} value={r}>{roleName(r)}</option>)}</select></Field>
  <Field label={c("Scope branch","لقی دەسەڵات","نطاق الفرع","Kapsam şubesi")} hint={c("Leave blank for group scope if your role permits it","ئەگەر ڕۆڵەکەت ڕێگە دەدات، بۆ ئاستی گرووپ بەتاڵی بهێڵەرەوە","اتركه فارغاً لنطاق المجموعة إذا كان دورك يسمح","Rolünüz izin veriyorsa grup kapsamı için boş bırakın")}><select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">{c("Group / all allowed branches","گرووپ / هەموو لقە ڕێگەپێدراوەکان","المجموعة / كل الفروع المسموحة","Grup / izinli tüm şubeler")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>
  <Field label={c("Language","زمان","اللغة","Dil")}><select value={form.preferred_language} onChange={e=>setForm({...form,preferred_language:e.target.value})}><option value="en">English</option><option value="ku">کوردی (سۆرانی)</option><option value="ar">العربية</option><option value="tr">Türkçe</option></select></Field>
  <label className="check-field span-2"><input type="checkbox" checked={form.can_delegate} onChange={e=>setForm({...form,can_delegate:e.target.checked})}/><span>{c("Allow this manager to delegate lower roles inside this scope","ڕێگە بە ئەم بەڕێوەبەرە بدە ڕۆڵی نزمتر لە ناو ئەم ئاستەدا بسپێرێت","السماح لهذا المدير بتفويض أدوار أدنى ضمن هذا النطاق","Bu yöneticinin bu kapsamda daha düşük rolleri devretmesine izin ver")}</span></label>
  <div className="form-actions span-2"><Button variant="secondary" type="button" onClick={()=>setOpen(false)}>{c("Cancel","هەڵوەشاندنەوە","إلغاء","İptal")}</Button><Button>{c("Create user","دروستکردنی بەکارهێنەر","إنشاء مستخدم","Kullanıcı oluştur")}</Button></div>
 </form></Modal></div>
}
