import React,{useMemo,useState} from "react";
import {architectureModules} from "../data/modules";
import {Badge,PageHeader} from "../components/ui";
import {useI18n} from "../lib/i18nContext";
import {moduleTitle} from "../data/moduleLocale";
import {foundationOperationalCodes} from "../data/enterpriseNav";
export default function ArchitecturePage(){
 const {lang}=useI18n(),c=(en:string,ku:string,ar:string,tr:string)=>lang==="ku"?ku:lang==="ar"?ar:lang==="tr"?tr:en;
 const verticalName:Record<string,string>={P:c("Provider / SaaS Control Plane","دابینکەر / بەشی کۆنترۆڵی SaaS","المزوّد / لوحة تحكم SaaS","Sağlayıcı / SaaS Kontrol Düzlemi"),A:c("Platform Core","بنەمای پلاتفۆرم","نواة المنصة","Platform Çekirdeği"),B:c("School / K-12","قوتابخانە / K-12","المدارس / K-12","Okul / K-12"),C:c("Academy / After-School","ئەکادیمی / دوای قوتابخانە","الأكاديمية / ما بعد المدرسة","Akademi / Okul Sonrası"),D:c("Higher Education","خوێندنی باڵا","التعليم العالي","Yükseköğretim"),E:c("Extensions","پاشکۆکان","الإضافات","Eklentiler")};
 const [q,setQ]=useState(""),[v,setV]=useState("ALL");
 const filtered=useMemo(()=>architectureModules.filter(m=>(v==="ALL"||m.vertical===v)&&(`${m.code} ${moduleTitle(m.code,lang,m.title)}`.toLowerCase().includes(q.toLowerCase()))),[q,v,lang]);
 return <div><PageHeader title={c("Master Architecture Coverage","داپۆشینی Master Architecture","تغطية البنية الرئيسية","Ana Mimari Kapsamı")} description={c("Master Architecture V6 is embedded in the product. Every registered module now opens a working scoped workbench, while dedicated domain implementations continue to deepen module by module.","Master Architecture V6 لە ناو بەرهەمەکە جێگیرکراوە. هەموو ماژوولە تۆمارکراوەکان ئێستا ژینگەی کاری کارا و سنوورداریان هەیە، لە هەمان کاتدا جێبەجێکردنی تایبەتی هەر بوارێک بەردەوام قووڵتر دەکرێتەوە.","تم تضمين Master Architecture V6 في المنتج. كل وحدة مسجلة تفتح الآن مساحة عمل فعلية ومحددة النطاق، مع استمرار تعميق التنفيذ المتخصص لكل مجال.","Master Architecture V6 ürüne gömülüdür. Kayıtlı her modül artık çalışan ve kapsamlı bir çalışma alanı açar; alan bazlı özel uygulamalar modül modül derinleştirilmektedir.")}/>
 <div className="toolbar"><input placeholder={c("Search architecture modules…","گەڕان بەدوای ماژوولەکان…","البحث في وحدات البنية…","Mimari modüllerde ara…")} value={q} onChange={e=>setQ(e.target.value)}/><select value={v} onChange={e=>setV(e.target.value)}><option value="ALL">{c("All product packs","هەموو پاکێجەکان","كل الحزم","Tüm ürün paketleri")}</option>{Object.entries(verticalName).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></div>
 <div className="architecture-grid">{filtered.map(m=><article className="architecture-card" key={m.code}><div><Badge tone={foundationOperationalCodes.has(m.code)?"good":"info"}>{m.code}</Badge><small>{verticalName[m.vertical]}</small></div><h3>{moduleTitle(m.code,lang,m.title)}</h3><div className="arch-status">{foundationOperationalCodes.has(m.code)?c("Dedicated operational workspace + V6 workbench","ژینگەی کاری تایبەت + ژینگەی V6","مساحة تشغيل متخصصة + مساحة V6","Özel operasyon alanı + V6 çalışma alanı"):c("V6 operational workbench enabled","ژینگەی کاری V6 چالاکە","مساحة عمل V6 مفعلة","V6 operasyon çalışma alanı etkin")}</div></article>)}</div>
 </div>
}
