import React,{useEffect,useMemo,useState} from "react";
import {api,qs} from "../lib/api";
import {Badge,Button,Empty,Field,Modal,PageHeader,StatCard} from "../components/ui";
import {useI18n} from "../lib/i18nContext";

const tabIds=["Overview","Contacts & Owners","Subscription","Entitlements","Usage / Quotas","Provisioning","Domains / Branding","Implementation","Adoption / Health","Support / Incidents","Security / Compliance","Backups","Communications","Timeline","Provider Audit"];

export default function Customer360Page({tenantId,tenant,branches,onOpenTenantApp,onNavigate}:{tenantId:string,tenant:any,branches:any[],onOpenTenantApp:()=>void,onNavigate:(page:string)=>void}){
 const {lang,label}=useI18n(),c=(en:string,ku:string,ar:string,tr:string)=>lang==="ku"?ku:lang==="ar"?ar:lang==="tr"?tr:en;
 const tabName=(x:string)=>({"Overview":c("Overview","پوختە","نظرة عامة","Genel Bakış"),"Contacts & Owners":c("Contacts & Owners","پەیوەندی و خاوەنەکان","جهات الاتصال والمالكون","İletişim ve Sahipler"),"Subscription":c("Subscription","بەشداری","الاشتراك","Abonelik"),"Entitlements":c("Entitlements","ماف و تایبەتمەندییەکان","الاستحقاقات","Haklar"),"Usage / Quotas":c("Usage / Quotas","بەکارهێنان / سنوورەکان","الاستخدام / الحصص","Kullanım / Kotalar"),"Provisioning":c("Provisioning","ئامادەکردنی ژینگە","التجهيز","Hazırlama"),"Domains / Branding":c("Domains / Branding","دۆمەین / براندینگ","النطاقات / الهوية","Alan Adları / Marka"),"Implementation":c("Implementation","جێبەجێکردن","التنفيذ","Uygulama"),"Adoption / Health":c("Adoption / Health","بەکارهێنان / دۆخی کڕیار","التبني / الصحة","Benimseme / Sağlık"),"Support / Incidents":c("Support / Incidents","پشتگیری / ڕووداوەکان","الدعم / الحوادث","Destek / Olaylar"),"Security / Compliance":c("Security / Compliance","ئاسایش / پابەندبوون","الأمن / الامتثال","Güvenlik / Uyumluluk"),"Backups":c("Backups","پاڵپشتەکان","النسخ الاحتياطية","Yedekler"),"Communications":c("Communications","پەیوەندییەکان","الاتصالات","İletişim"),"Timeline":c("Timeline","هێڵی کات","الخط الزمني","Zaman Çizelgesi"),"Provider Audit":c("Provider Audit","پشکنینی پلاتفۆرم","تدقيق المزوّد","Sağlayıcı Denetimi")}[x]||label(x));
 const [active,setActive]=useState(0),[users,setUsers]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]);
 const [tabRows,setTabRows]=useState<any[]>([]),[canWrite,setCanWrite]=useState(false),[tabLoading,setTabLoading]=useState(false),[tabError,setTabError]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState({title:"",status:"active",description:""});
 useEffect(()=>{if(!tenantId)return;Promise.all([api<any>("/api/users"+qs({tenant_id:tenantId})).catch(()=>({rows:[]})),api<any>("/api/students"+qs({tenant_id:tenantId})).catch(()=>({rows:[]})),api<any>("/api/staff"+qs({tenant_id:tenantId})).catch(()=>({rows:[]}))]).then(([u,s,st])=>{setUsers(u.rows||[]);setStudents(s.rows||[]);setStaff(st.rows||[])})},[tenantId]);
 const owners=useMemo(()=>users.filter(u=>(u.assignments||[]).some((a:any)=>a.role_code==="tenant_owner")),[users]),loginUrl=location.origin,renewal=tenant?.expires_at?new Date(tenant.expires_at).toLocaleDateString(lang==="ku"?"ku-Arab":lang):"—",copyLogin=()=>navigator.clipboard?.writeText(loginUrl);
 const sectionKey=active?`${tenantId}::${tabIds[active]}`:"";
 async function loadTab(){if(!active)return;setTabLoading(true);setTabError("");try{const r=await api<any>(`/api/modules/P02/records${qs({section:sectionKey})}`);setTabRows(r.rows||[]);setCanWrite(!!r.can_write)}catch(e:any){setTabError(e.message);setCanWrite(false)}finally{setTabLoading(false)}}
 useEffect(()=>{loadTab()},[active,tenantId]);
 function start(row:any=null){if(!canWrite)return;setEdit(row);setForm(row?{title:row.title,status:row.status,description:row.description||""}:{title:"",status:"active",description:""});setModal(true)}
 async function save(e:React.FormEvent){e.preventDefault();try{const body={title:form.title,status:form.status,description:form.description,record_type:"customer_360",section_key:sectionKey,data:{target_tenant_id:tenantId,target_tenant_name:tenant?.name,workspace:tabIds[active]}};if(edit)await api(`/api/modules/P02/records/${edit.id}`,{method:"PATCH",body:JSON.stringify(body)});else await api("/api/modules/P02/records",{method:"POST",body:JSON.stringify(body)});setModal(false);await loadTab()}catch(e:any){setTabError(e.message)}}
 async function archive(row:any){if(!canWrite)return;await api(`/api/modules/P02/records/${row.id}`,{method:"DELETE"});await loadTab()}

 const overview=<><div className="stats-grid customer-stats"><StatCard label={c("Branches / Campuses","لق / کامپەسەکان","الفروع / الحُرُم","Şubeler / Kampüsler")} value={branches.length} meta={c("Active organization scope","ئاستی چالاکی ڕێکخراو","نطاق المؤسسة النشط","Aktif organizasyon kapsamı")}/><StatCard label={c("Students","قوتابیان","الطلاب","Öğrenciler")} value={students.length} meta={c("Current records","تۆمارە ئێستاکان","السجلات الحالية","Mevcut kayıtlar")}/><StatCard label={c("Staff / Teachers","کارمەند / مامۆستا","الموظفون / المعلمون","Personel / Öğretmenler")} value={staff.length} meta={c("Current records","تۆمارە ئێستاکان","السجلات الحالية","Mevcut kayıtlar")}/><StatCard label={c("Tenant Owners","خاوەنانی کڕیار","مالكو العميل","Müşteri Sahipleri")} value={owners.length} meta={c("Account ownership","خاوەندارێتی هەژمار","ملكية الحساب","Hesap sahipliği")}/><StatCard label={c("Renewal / Expiry","نوێکردنەوە / بەسەرچوون","التجديد / الانتهاء","Yenileme / Bitiş")} value={renewal} meta={tenant?.plan_code||c("Plan not set","پلان دیاری نەکراوە","لم تُحدد الخطة","Plan belirlenmedi")}/></div>
 <div className="grid-2 mt"><section className="panel"><div className="panel-head"><h3>{c("Customer access","دەستگەیشتنی کڕیار","وصول العميل","Müşteri erişimi")}</h3><Badge tone={owners.length?"good":"warn"}>{owners.length?c("Owner configured","خاوەن ڕێکخراوە","المالك مضبوط","Sahip hazır"):c("Owner required","خاوەن پێویستە","المالك مطلوب","Sahip gerekli")}</Badge></div><div className="customer-access-card"><div><span>Login URL</span><strong>{loginUrl}</strong></div><div className="customer-access-actions"><Button variant="secondary" onClick={copyLogin}>{c("Copy login URL","کۆپی لینکی چوونەژوورەوە","نسخ رابط الدخول","Giriş URL'sini kopyala")}</Button><Button onClick={onOpenTenantApp}>{c("Open tenant application","کردنەوەی بەشی کڕیار","فتح تطبيق العميل","Müşteri uygulamasını aç")}</Button></div></div><div className="owner-list">{owners.length?owners.map(o=><div key={o.id}><div className="avatar small">{o.name?.slice(0,1)?.toUpperCase()}</div><div><strong>{o.name}</strong><span>{o.email}</span></div><Badge tone="good">{c("Tenant Owner","خاوەنی کڕیار","مالك العميل","Müşteri Sahibi")}</Badge></div>):<p className="muted-text">{c("No Tenant Owner is assigned. Create one from Users & Delegated Access before giving the customer access.","هیچ خاوەنی کڕیارێک دیاری نەکراوە. پێش سپاردنی دەستگەیشتن بە کڕیار، لە «بەکارهێنەران و دەسەڵاتی سپێردراو» یەکێک دروست بکە.","لم يُعيّن مالك للعميل. أنشئ واحداً من المستخدمين والصلاحيات المفوضة قبل تسليم الوصول للعميل.","Müşteri Sahibi atanmadı. Müşteriye erişim vermeden önce Kullanıcılar ve Yetkilendirilmiş Erişim bölümünden bir tane oluşturun.")}</p>}</div></section>
 <section className="panel"><div className="panel-head"><h3>{c("Account 360 status","دۆخی هەژماری 360","حالة حساب 360","Hesap 360 durumu")}</h3><Badge tone="info">P02</Badge></div><div className="status-stack"><div><span>{c("Customer status","دۆخی کڕیار","حالة العميل","Müşteri durumu")}</span><strong>{tenant?.status||"—"}</strong></div><div><span>{c("Plan","پلان","الخطة","Plan")}</span><strong>{tenant?.plan_code||"—"}</strong></div><div><span>{c("Country","وڵات","الدولة","Ülke")}</span><strong>{tenant?.country||"—"}</strong></div><div><span>{c("Default currency","دراوی بنەڕەتی","العملة الافتراضية","Varsayılan para birimi")}</span><strong>{tenant?.default_currency||"—"}</strong></div><div><span>{c("Default language","زمانی بنەڕەتی","اللغة الافتراضية","Varsayılan dil")}</span><strong>{tenant?.default_language||"—"}</strong></div></div></section></div>
 <section className="panel mt"><div className="panel-head"><h3>{c("Account team & action center","تیمی هەژمار و ناوەندی کردار","فريق الحساب ومركز الإجراءات","Hesap ekibi ve işlem merkezi")}</h3><Badge tone="neutral">V6</Badge></div><div className="action-grid">{[c("Commercial owner","بەرپرسی بازرگانی","مسؤول تجاري","Ticari sorumlu"),c("Customer success owner","بەرپرسی سەرکەوتنی کڕیار","مسؤول نجاح العميل","Müşteri başarısı sorumlusu"),c("Implementation lead","بەرپرسی جێبەجێکردن","مسؤول التنفيذ","Uygulama lideri"),c("Support owner","بەرپرسی پشتگیری","مسؤول الدعم","Destek sorumlusu"),c("Security / privacy contact","پەیوەندی ئاسایش / تایبەتمەندی","جهة اتصال الأمن / الخصوصية","Güvenlik / gizlilik kişisi"),c("Technical contact","پەیوەندی تەکنیکی","جهة الاتصال التقنية","Teknik kişi")].map(x=><div className="action-tile" key={x}><span>{x}</span><strong>{c("Not assigned","دیاری نەکراوە","غير معيّن","Atanmadı")}</strong><button onClick={()=>setActive(1)}>{c("Assign","دیاریکردن","تعيين","Ata")}</button></div>)}</div></section></>;

 const workingTab=<section className="panel customer-tab-placeholder operational-customer-tab"><div className="workspace-section-head"><div><span className="eyebrow">P02 · CUSTOMER / TENANT 360</span><h2>{tabName(tabIds[active])}</h2><p>{c("Operational records for this customer workspace are stored, scoped and audited.","تۆمارە کارپێکردنییەکانی ئەم ژینگەی کڕیارە هەڵدەگیرێن، سنووردارن و پشکنینیان بۆ دەکرێت.","تُحفظ سجلات هذا المجال للعميل ضمن نطاق محدد وتخضع للتدقيق.","Bu müşteri alanındaki operasyon kayıtları saklanır, kapsamlandırılır ve denetlenir.")}</p></div><div>{canWrite?<Button onClick={()=>start()}>+ {c("New record","تۆماری نوێ","سجل جديد","Yeni kayıt")}</Button>:<Badge tone="neutral">{c("Read only","تەنها خوێندنەوە","قراءة فقط","Salt okunur")}</Badge>}</div></div>{tabError&&<div className="alert alert-error">{tabError}</div>}{tabLoading?<div className="empty-line">{c("Loading…","بار دەکرێت…","جارٍ التحميل…","Yükleniyor…")}</div>:!tabRows.length?<Empty title={c("No records yet","هێشتا هیچ تۆمارێک نییە","لا توجد سجلات بعد","Henüz kayıt yok")} description={c("Create the first customer-specific record for this workspace.","یەکەم تۆماری تایبەت بە کڕیار بۆ ئەم ژینگەی کارە دروست بکە.","أنشئ أول سجل خاص بالعميل في هذا المجال.","Bu çalışma alanı için ilk müşteri kaydını oluşturun.")}/>:<div className="workbench-record-list">{tabRows.map(r=><article className="workbench-record" key={r.id}><div className="record-main"><div className="record-title-row"><strong>{r.title}</strong><Badge tone={r.status==="active"||r.status==="approved"?"good":"info"}>{label(r.status)}</Badge></div><p>{r.description||tabName(tabIds[active])}</p><div className="record-meta"><span>{c("Updated","نوێکراوەتەوە","تم التحديث","Güncellendi")}: {new Date(r.updated_at).toLocaleString(lang==="ku"?"ku-Arab":lang)}</span><span>{r.owner_name||r.created_by_name||"—"}</span></div></div>{canWrite&&<div className="record-actions"><Button variant="secondary" onClick={()=>start(r)}>{c("Edit","دەستکاری","تعديل","Düzenle")}</Button>{r.status!=="archived"&&<Button variant="ghost" onClick={()=>archive(r)}>{c("Archive","ئەرشیف","أرشفة","Arşivle")}</Button>}</div>}</article>)}</div>}</section>;

 return <div><div className="customer-360-hero"><PageHeader title={tenant?.name||c("Customer / Tenant 360","کڕیار 360","العميل 360","Müşteri 360")} description={`P02 · ${c("Customer workspace","ژینگەی کاری کڕیار","مساحة عمل العميل","Müşteri çalışma alanı")} · ID ${tenantId}`} actions={<><Button variant="secondary" onClick={()=>onNavigate("customers")}>← {c("Directory","کڕیاران","الدليل","Dizin")}</Button><Button onClick={onOpenTenantApp}>{c("Enter tenant application","چوونە بەشی کڕیار","دخول تطبيق العميل","Müşteri uygulamasına gir")}</Button></>}/><div className="customer-meta-row"><Badge tone={tenant?.status==="active"||tenant?.status==="trial"?"good":"warn"}>{label(tenant?.status||"unknown")}</Badge><span>{c("Plan","پلان","الخطة","Plan")}: <strong>{tenant?.plan_code||"—"}</strong></span><span>{c("Renewal","نوێکردنەوە","التجديد","Yenileme")}: <strong>{renewal}</strong></span><span>Slug: <strong>{tenant?.slug||"—"}</strong></span></div></div>
 <div className="workspace-tabs customer-tabs">{tabIds.map((x,i)=><button key={x} className={active===i?"active":""} onClick={()=>setActive(i)}>{tabName(x)}</button>)}</div>{active===0?overview:workingTab}
 <Modal open={modal} onClose={()=>setModal(false)} title={edit?c("Edit record","دەستکاری تۆمار","تعديل السجل","Kaydı düzenle"):c("New customer record","تۆماری نوێی کڕیار","سجل عميل جديد","Yeni müşteri kaydı")} width={680}><form className="form-stack" onSubmit={save}><Field label={c("Title","ناونیشان","العنوان","Başlık")}><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label={c("Status","دۆخ","الحالة","Durum")}><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">{c("Active","چالاک","نشط","Aktif")}</option><option value="pending">{c("Pending","چاوەڕوان","قيد الانتظار","Bekliyor")}</option><option value="approved">{c("Approved","پەسەندکراو","معتمد","Onaylandı")}</option><option value="completed">{c("Completed","تەواوکراو","مكتمل","Tamamlandı")}</option><option value="draft">{c("Draft","ڕەشنووس","مسودة","Taslak")}</option></select></Field><Field label={c("Details / notes","وردەکاری / تێبینی","التفاصيل / الملاحظات","Ayrıntılar / notlar")}><textarea rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setModal(false)}>{c("Cancel","هەڵوەشاندنەوە","إلغاء","İptal")}</Button><Button>{c("Save","پاشەکەوتکردن","حفظ","Kaydet")}</Button></div></form></Modal>
 </div>
}
