import React,{useEffect,useMemo,useState} from "react";
import {api} from "../lib/api";
import {Badge,Button,DataTable,Field,Modal,PageHeader} from "../components/ui";
import {useI18n} from "../lib/i18nContext";
const tone=(s:string)=>["active","trial"].includes(s)?"good":["renewal_due","grace"].includes(s)?"warn":["suspended","cancelled"].includes(s)?"bad":"neutral";
const makePassword=()=>`Edu-${crypto.randomUUID().slice(0,8)}!${Math.floor(Math.random()*90+10)}`;

export default function CustomersPage({onChanged,onOpenTenant}:{onChanged:()=>void,onOpenTenant:(id:string)=>void}){
  const {lang,label}=useI18n();
  const c=(en:string,ku:string,ar:string,tr:string)=>lang==="ku"?ku:lang==="ar"?ar:lang==="tr"?tr:en;
  const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(""),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null);
  const [form,setForm]=useState<any>({name:"",slug:"",plan_code:"trial",country:"Iraq",default_currency:"IQD",default_language:"en",timezone:"Asia/Baghdad",owner_name:"",owner_email:"",owner_password:makePassword(),create_branch:true,branch_name:"Main Campus",branch_code:"MAIN"});
  const load=()=>api<any>("/api/tenants").then(r=>setRows(r.rows));
  useEffect(()=>{load()},[]);
  const canNext=useMemo(()=>step===1?!!form.name:step===2?!!form.owner_name&&!!form.owner_email&&String(form.owner_password).length>=10:step===3?!form.create_branch|| (!!form.branch_name&&!!form.branch_code):true,[step,form]);
  function start(){setError("");setResult(null);setStep(1);setForm((x:any)=>({...x,name:"",slug:"",owner_name:"",owner_email:"",owner_password:makePassword(),branch_name:"Main Campus",branch_code:"MAIN",create_branch:true}));setOpen(true)}
  async function provision(){setBusy(true);setError("");try{const tenantResponse=await api<any>("/api/tenants",{method:"POST",body:JSON.stringify({name:form.name,slug:form.slug||undefined,plan_code:form.plan_code,country:form.country,default_currency:form.default_currency,default_language:form.default_language,timezone:form.timezone})});const tenantId=tenantResponse.id;await api("/api/users",{method:"POST",body:JSON.stringify({tenant_id:tenantId,branch_id:null,name:form.owner_name,email:form.owner_email,password:form.owner_password,role_code:"tenant_owner",can_delegate:true,preferred_language:form.default_language})});let branchId:string|null=null;if(form.create_branch){const b=await api<any>("/api/branches",{method:"POST",body:JSON.stringify({tenant_id:tenantId,name:form.branch_name,code:form.branch_code,type:"school"})});branchId=b.id}setResult({tenant_id:tenantId,branch_id:branchId,login_url:location.origin,password:form.owner_password,email:form.owner_email});setStep(5);load();onChanged()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const copy=(v:string)=>navigator.clipboard?.writeText(v);
  const steps=[c("Organization","ڕێکخراو","المؤسسة","Organizasyon"),c("Initial Owner","بەڕێوەبەری یەکەم","المالك الأول","İlk Sahip"),c("First Branch","یەکەم لق","الفرع الأول","İlk Şube"),c("Review","پێداچوونەوە","مراجعة","İnceleme")];
  return <div>
    <PageHeader title={c("Customer / Tenant Directory","بەڕێوەبردنی کڕیاران","دليل العملاء","Müşteri Dizini")} description={c("P02 · Search, provision and manage customer accounts as isolated subscription scopes.","P02 · گەڕان، دروستکردن و بەڕێوەبردنی هەژماری کڕیاران وەک ژینگەی بەشداریی جیاکراوە.","P02 · البحث عن حسابات العملاء وتجهيزها وإدارتها كنطاقات اشتراك معزولة.","P02 · Müşteri hesaplarını izole abonelik kapsamları olarak arayın, hazırlayın ve yönetin.")} actions={<Button onClick={start}>+ {c("Provision customer","دروستکردنی کڕیار","تجهيز عميل","Müşteri hazırla")}</Button>}/>
    <div className="directory-toolbar panel"><div className="directory-summary"><div><span>{c("Customers","کڕیاران","العملاء","Müşteriler")}</span><strong>{rows.length}</strong></div><div><span>{c("Active / Trial","چالاک / تاقیکردنەوە","نشط / تجريبي","Aktif / Deneme")}</span><strong>{rows.filter(x=>["active","trial"].includes(x.status)).length}</strong></div><div><span>{c("Renewal due","نوێکردنەوە نزیکە","التجديد مستحق","Yenileme zamanı")}</span><strong>{rows.filter(x=>x.status==="renewal_due").length}</strong></div></div><div className="saved-view-chip">{c("Default view · All customers","دیمەنی بنەڕەتی · هەموو کڕیاران","العرض الافتراضي · جميع العملاء","Varsayılan görünüm · Tüm müşteriler")}</div></div>
    <div className="panel mt"><DataTable rows={rows} columns={[
      {key:"name",label:c("Customer","کڕیار","العميل","Müşteri"),render:r=><button className="link-btn" onClick={()=>onOpenTenant(r.id)}><strong>{r.name}</strong><small>{r.slug}</small></button>},
      {key:"status",label:c("Status","دۆخ","الحالة","Durum"),render:r=><Badge tone={tone(r.status) as any}>{label(r.status)}</Badge>},{key:"plan_name",label:c("Plan","پلان","الخطة","Plan")},{key:"branch_count",label:c("Branches","لقەکان","الفروع","Şubeler")},{key:"student_count",label:c("Students","قوتابیان","الطلاب","Öğrenciler")},{key:"staff_count",label:c("Staff","کارمەندان","الموظفون","Personel")},{key:"expires_at",label:c("Renewal / Expiry","نوێکردنەوە / بەسەرچوون","التجديد / الانتهاء","Yenileme / Bitiş"),render:r=>r.expires_at?new Date(r.expires_at).toLocaleDateString(lang==="ku"?"ku-Arab":lang):"—"}
    ]}/></div>

    <Modal open={open} onClose={()=>!busy&&setOpen(false)} title={c("Provision customer tenant","دروستکردنی ژینگەی کڕیار","تجهيز حساب العميل","Müşteri ortamını hazırla")} width={860}>
      <div className="wizard-steps">{steps.map((x,i)=><div className={`${step===i+1?"active":""} ${step>i+1?"done":""}`} key={x}><span>{step>i+1?"✓":i+1}</span><strong>{x}</strong></div>)}</div>{error&&<div className="alert alert-error">{error}</div>}
      {step===1&&<div className="wizard-pane"><div className="wizard-intro"><span className="eyebrow">P09 · {c("PROVISIONING REQUEST","داواکاری ئامادەکردن","طلب التجهيز","HAZIRLAMA TALEBİ")}</span><h3>{c("Customer organization","ڕێکخراوی کڕیار","مؤسسة العميل","Müşteri organizasyonu")}</h3><p>{c("Create the customer identity, commercial baseline and regional defaults.","ناسنامەی کڕیار، بنەمای بازرگانی و ڕێکخستنە هەرێمییەکان دروست بکە.","أنشئ هوية العميل والأساس التجاري والإعدادات الإقليمية.","Müşteri kimliğini, ticari temeli ve bölgesel varsayılanları oluşturun.")}</p></div><div className="form-grid">
        <Field label={c("Customer / group name","ناوی کڕیار / گرووپ","اسم العميل / المجموعة","Müşteri / grup adı")}><input autoFocus required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Slug" hint={c("Optional; generated from name if blank","ئارەزوومەندانە؛ ئەگەر بەتاڵ بێت لە ناوەکە دروست دەکرێت","اختياري؛ يُنشأ من الاسم إذا تُرك فارغاً","İsteğe bağlı; boşsa addan oluşturulur")}><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></Field>
        <Field label={c("Plan","پلان","الخطة","Plan")}><select value={form.plan_code} onChange={e=>setForm({...form,plan_code:e.target.value})}><option value="trial">Trial</option><option value="starter">Starter</option><option value="professional">Professional</option><option value="enterprise">Enterprise</option></select></Field><Field label={c("Country","وڵات","الدولة","Ülke")}><input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Field><Field label={c("Currency","دراو","العملة","Para Birimi")}><select value={form.default_currency} onChange={e=>setForm({...form,default_currency:e.target.value})}><option>IQD</option><option>USD</option><option>EUR</option></select></Field><Field label={c("Language","زمان","اللغة","Dil")}><select value={form.default_language} onChange={e=>setForm({...form,default_language:e.target.value})}><option value="en">English</option><option value="ku">کوردی (سۆرانی)</option><option value="ar">العربية</option><option value="tr">Türkçe</option></select></Field><Field label={c("Timezone","ناوچەی کاتی","المنطقة الزمنية","Saat Dilimi")}><input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field>
      </div></div>}
      {step===2&&<div className="wizard-pane"><div className="wizard-intro"><span className="eyebrow">P09 · {c("INITIAL OWNER","بەڕێوەبەری یەکەم","المالك الأول","İLK SAHİP")}</span><h3>{c("Create the Tenant Owner","دروستکردنی بەڕێوەبەری کڕیار","إنشاء مالك العميل","Müşteri Sahibını oluştur")}</h3><p>{c("This is the customer's first administrative account. It signs in from the same application URL and is automatically restricted to this tenant.","ئەمە یەکەم هەژماری بەڕێوەبردنی کڕیارە. لە هەمان لینکی سیستەمەوە دەچێتە ژوورەوە و خۆکارانە تەنها بە ژینگەی خۆی دەستگەیشتن هەیە.","هذا أول حساب إداري للعميل. يسجل الدخول من نفس رابط التطبيق ويُقيّد تلقائياً بنطاق العميل.","Bu müşterinin ilk yönetici hesabıdır. Aynı uygulama adresinden giriş yapar ve otomatik olarak yalnızca kendi müşteri kapsamına sınırlandırılır.")}</p></div><div className="form-grid"><Field label={c("Owner full name","ناوی تەواوی بەڕێوەبەر","الاسم الكامل للمالك","Sahibin adı soyadı")}><input autoFocus required value={form.owner_name} onChange={e=>setForm({...form,owner_name:e.target.value})}/></Field><Field label={c("Owner email","ئیمەیڵی بەڕێوەبەر","بريد المالك","Sahip e-postası")}><input required type="email" value={form.owner_email} onChange={e=>setForm({...form,owner_email:e.target.value})}/></Field><Field label={c("Temporary password","وشەی نهێنی کاتی","كلمة المرور المؤقتة","Geçici parola")} hint={c("Minimum 10 characters; shown once after provisioning","لانیکەم ١٠ پیت؛ دوای دروستکردن تەنها یەکجار نیشان دەدرێت","10 أحرف على الأقل؛ تظهر مرة واحدة بعد التجهيز","En az 10 karakter; hazırlamadan sonra bir kez gösterilir")}><input required minLength={10} value={form.owner_password} onChange={e=>setForm({...form,owner_password:e.target.value})}/></Field><div className="field"><span>{c("Password helper","یاریدەدەری وشەی نهێنی","مساعد كلمة المرور","Parola yardımcısı")}</span><Button type="button" variant="secondary" onClick={()=>setForm({...form,owner_password:makePassword()})}>{c("Generate secure password","دروستکردنی وشەی نهێنی پارێزراو","توليد كلمة مرور آمنة","Güvenli parola üret")}</Button></div></div></div>}
      {step===3&&<div className="wizard-pane"><div className="wizard-intro"><span className="eyebrow">A02 · {c("ORGANIZATION STRUCTURE","پێکهاتەی ڕێکخراو","هيكل المؤسسة","ORGANİZASYON YAPISI")}</span><h3>{c("First branch / campus","یەکەم لق / کامپەس","الفرع / الحرم الأول","İlk şube / kampüs")}</h3><p>{c("Optionally create the first operational branch so the customer can start school configuration immediately.","ئەگەر بتەوێت یەکەم لقی کارپێکردن دروست بکە تاکو کڕیار بتوانێت دەستبەجێ ڕێکخستنی قوتابخانە دەست پێ بکات.","يمكنك إنشاء أول فرع تشغيلي ليبدأ العميل إعداد المدرسة مباشرة.","İsterseniz müşterinin okul yapılandırmasına hemen başlayabilmesi için ilk operasyonel şubeyi oluşturun.")}</p></div><label className="toggle-row"><input type="checkbox" checked={form.create_branch} onChange={e=>setForm({...form,create_branch:e.target.checked})}/><div><strong>{c("Create first branch now","ئێستا یەکەم لق دروست بکە","إنشاء الفرع الأول الآن","İlk şubeyi şimdi oluştur")}</strong><span>{c("Recommended for school tenants","بۆ کڕیاری قوتابخانە پێشنیار دەکرێت","موصى به لعملاء المدارس","Okul müşterileri için önerilir")}</span></div></label>{form.create_branch&&<div className="form-grid mt"><Field label={c("Branch / campus name","ناوی لق / کامپەس","اسم الفرع / الحرم","Şube / kampüs adı")}><input autoFocus required value={form.branch_name} onChange={e=>setForm({...form,branch_name:e.target.value})}/></Field><Field label={c("Branch code","کۆدی لق","رمز الفرع","Şube kodu")}><input required value={form.branch_code} onChange={e=>setForm({...form,branch_code:e.target.value.toUpperCase()})}/></Field></div>}</div>}
      {step===4&&<div className="wizard-pane"><div className="wizard-intro"><span className="eyebrow">{c("PROVISIONING REVIEW","پێداچوونەوەی دروستکردن","مراجعة التجهيز","HAZIRLAMA İNCELEMESİ")}</span><h3>{c("Ready to create tenant","ئامادەی دروستکردنی کڕیارە","جاهز لإنشاء العميل","Müşteriyi oluşturmaya hazır")}</h3><p>{c("This workflow creates the customer, subscription baseline, initial owner and optional first branch together.","ئەم ڕەوتە کڕیار، بنەمای بەشداری، بەڕێوەبەری یەکەم و ئەگەر هەڵبژێردرا یەکەم لق پێکەوە دروست دەکات.","ينشئ هذا المسار العميل وأساس الاشتراك والمالك الأول والفرع الأول الاختياري معاً.","Bu akış müşteriyi, abonelik temelini, ilk sahibi ve isteğe bağlı ilk şubeyi birlikte oluşturur.")}</p></div><div className="review-grid"><div><span>{c("Customer","کڕیار","العميل","Müşteri")}</span><strong>{form.name}</strong></div><div><span>{c("Plan","پلان","الخطة","Plan")}</span><strong>{form.plan_code}</strong></div><div><span>{c("Owner","بەڕێوەبەر","المالك","Sahip")}</span><strong>{form.owner_name}</strong><small>{form.owner_email}</small></div><div><span>{c("First branch","یەکەم لق","الفرع الأول","İlk şube")}</span><strong>{form.create_branch?form.branch_name:c("Not created","دروست ناکرێت","لن يُنشأ","Oluşturulmayacak")}</strong><small>{form.create_branch?form.branch_code:c("Customer will configure later","کڕیار دواتر ڕێکی دەخات","سيعدّه العميل لاحقاً","Müşteri daha sonra yapılandıracak")}</small></div><div><span>{c("Locale","ناوچە و دراو","الإعداد المحلي","Yerel Ayarlar")}</span><strong>{form.country} · {form.default_currency}</strong><small>{form.timezone}</small></div><div><span>{c("Login","چوونەژوورەوە","الدخول","Giriş")}</span><strong>{location.origin}</strong></div></div></div>}
      {step===5&&result&&<div className="provision-success"><div className="success-mark">✓</div><h3>{c("Customer tenant is ready","ژینگەی کڕیار ئامادەیە","حساب العميل جاهز","Müşteri ortamı hazır")}</h3><p>{c("The customer can now sign in with the Tenant Owner account below.","کڕیار ئێستا دەتوانێت بە هەژماری بەڕێوەبەری خوارەوە بچێتە ژوورەوە.","يمكن للعميل الآن تسجيل الدخول بحساب المالك أدناه.","Müşteri artık aşağıdaki sahip hesabıyla giriş yapabilir.")}</p><div className="credential-card"><div><span>Login URL</span><strong>{result.login_url||location.origin}</strong><button onClick={()=>copy(result.login_url||location.origin)}>{c("Copy","کۆپی","نسخ","Kopyala")}</button></div><div><span>Email</span><strong>{result.email}</strong><button onClick={()=>copy(result.email)}>{c("Copy","کۆپی","نسخ","Kopyala")}</button></div><div><span>{c("Temporary password","وشەی نهێنی کاتی","كلمة المرور المؤقتة","Geçici parola")}</span><strong>{result.password}</strong><button onClick={()=>copy(result.password)}>{c("Copy","کۆپی","نسخ","Kopyala")}</button></div></div><div className="provision-warning">{c("Store or send the temporary password securely. The readable password is not stored by the platform.","وشەی نهێنی کاتی بە شێوەی پارێزراو هەڵبگرە یان بنێرە. پلاتفۆرم دەقی خوێندراوەی وشەی نهێنی هەڵناگرێت.","احفظ أو أرسل كلمة المرور المؤقتة بشكل آمن. المنصة لا تخزن كلمة المرور المقروءة.","Geçici parolayı güvenli şekilde saklayın veya gönderin. Platform okunabilir parolayı saklamaz.")}</div><div className="form-actions"><Button variant="secondary" onClick={()=>setOpen(false)}>{c("Close","داخستن","إغلاق","Kapat")}</Button><Button onClick={()=>{setOpen(false);onOpenTenant(result.tenant_id)}}>{c("Open Customer 360","کردنەوەی کڕیار 360","فتح العميل 360","Müşteri 360'ı aç")}</Button></div></div>}
      {step<5&&<div className="wizard-actions"><Button type="button" variant="secondary" disabled={step===1||busy} onClick={()=>setStep(step-1)}>{c("Back","گەڕانەوە","رجوع","Geri")}</Button><div><span>{c(`Step ${step} of 4`,`هەنگاوی ${step} لە ٤`,`الخطوة ${step} من 4`,`Adım ${step} / 4`)}</span>{step<4?<Button type="button" disabled={!canNext} onClick={()=>setStep(step+1)}>{c("Continue","بەردەوامبوون","متابعة","Devam")}</Button>:<Button type="button" disabled={!canNext||busy} onClick={provision}>{busy?c("Provisioning…","دروست دەکرێت…","جارٍ التجهيز…","Hazırlanıyor…"):c("Provision tenant","دروستکردنی کڕیار","تجهيز العميل","Müşteriyi hazırla")}</Button>}</div></div>}
    </Modal>
  </div>
}
