import React,{useCallback,useEffect,useMemo,useState} from "react";
import {architectureModules} from "../data/modules";
import {moduleSections} from "../data/moduleSections";
import {Badge,Button,Empty,Field,Modal,PageHeader} from "../components/ui";
import {foundationOperationalCodes,operationalRouteByCode} from "../data/enterpriseNav";
import {api,qs} from "../lib/api";
import {useI18n} from "../lib/i18nContext";

const depth=["Entities","Relationships","States","Actions","Validation","Business Rules","Workflows","Approvals","Permissions","Data Scope","Events","Automations","Notifications","Audit","Configuration","Integrations","API","Reports","KPIs","Retention","Privacy"];
const statuses=["draft","active","pending","approved","completed","archived"];
const lenses=[
 {id:"records",keys:["overview","records"],type:"general",icon:"▦"},{id:"workflow",keys:["workflow","approvals"],type:"workflow",icon:"⇄"},{id:"access",keys:["permissions","dataScope"],type:"access_review",icon:"◇"},{id:"automation",keys:["events","automations"],type:"automation",icon:"⚡"},{id:"reports",keys:["reports","kpis"],type:"report",icon:"▥"},{id:"config",keys:["configuration","auditTrail"],type:"configuration",icon:"⚙"}
];

type Props={code:string;tenantId:string|null;branchId:string|null;onNavigate:(route:string)=>void};
export default function ModuleWorkbenchPage({code,tenantId,branchId,onNavigate}:Props){
 const {lang,t,label,module:moduleName}=useI18n(),mod=architectureModules.find(m=>m.code===code);
 const [tab,setTab]=useState(0),[lens,setLens]=useState("records"),[rows,setRows]=useState<any[]>([]),[activity,setActivity]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("");
 const [form,setForm]=useState<any>({title:"",record_type:"general",status:"draft",description:""});
 const sections=moduleSections[code]||["Workspace"],section=sections[Math.min(tab,sections.length-1)]||"Workspace",current=lenses.find(x=>x.id===lens)||lenses[0],isLive=foundationOperationalCodes.has(code);
 const params={tenant_id:tenantId||undefined,branch_id:branchId||undefined,section,status:filter||undefined,q:query||undefined};
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [r,a]=await Promise.all([api<any>(`/api/modules/${code}/records${qs(params)}`),api<any>(`/api/modules/${code}/activity${qs({tenant_id:tenantId||undefined,branch_id:branchId||undefined})}`).catch(()=>({rows:[]}))]);setRows(r.rows||[]);setActivity(a.rows||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}},[code,tenantId,branchId,section,filter,query]);
 useEffect(()=>{load()},[load]);
 const shown=useMemo(()=>rows.filter(r=>lens==="records"||r.record_type===current.type),[rows,lens,current.type]);
 const lensTitle=(x:any)=>x.keys.map((k:string)=>t(k)).join(" / "),statusText=(s:string)=>t(s)||s,statusTone=(s:string)=>["active","approved","completed"].includes(s)?"good":s==="pending"?"warn":s==="archived"?"neutral":"info";
 function start(type=current.type,row:any=null){setEditing(row);setForm(row?{title:row.title,record_type:row.record_type,status:row.status,description:row.description||""}:{title:"",record_type:type,status:"draft",description:""});setModal(true)}
 async function save(e:React.FormEvent){e.preventDefault();try{const body={...form,tenant_id:tenantId,branch_id:branchId,section_key:section,data:{lens}};if(editing)await api(`/api/modules/${code}/records/${editing.id}`,{method:"PATCH",body:JSON.stringify(body)});else await api(`/api/modules/${code}/records`,{method:"POST",body:JSON.stringify(body)});setModal(false);await load()}catch(e:any){setError(e.message)}}
 async function archive(row:any){if(!confirm(`${t("archived")}: ${row.title}?`))return;try{await api(`/api/modules/${code}/records/${row.id}`,{method:"DELETE"});await load()}catch(e:any){setError(e.message)}}
 if(!mod)return <div className="panel"><h3>Module not found</h3></div>;
 const pack=code[0]==="P"?t("providerPlane"):code[0]==="A"?(lang==="ku"?"بنەمای پلاتفۆرم":lang==="ar"?"نواة المنصة":lang==="tr"?"Platform Çekirdeği":"Platform Core"):code[0]==="B"?(lang==="ku"?"پاکێجی قوتابخانە / K-12":lang==="ar"?"حزمة المدارس / K-12":lang==="tr"?"Okul / K-12 Paketi":"School / K-12 Pack"):code[0]==="C"?(lang==="ku"?"پاکێجی ئەکادیمی":lang==="ar"?"حزمة الأكاديمية":lang==="tr"?"Akademi Paketi":"Academy Pack"):(lang==="ku"?"پاکێجی خوێندنی باڵا":lang==="ar"?"حزمة التعليم العالي":lang==="tr"?"Yükseköğretim Paketi":"Higher-Education Pack");
 return <div className="module-workspace operational-module-workspace">
  <PageHeader title={`${code} · ${moduleName(code,mod.title)}`} description={`${pack} · ${t("sourceArchitecture")} · #${mod.line}`} actions={<div className="page-actions"><Badge tone="good">{t("moduleWorkbench")}</Badge>{isLive&&operationalRouteByCode[code]&&<Button variant="secondary" onClick={()=>onNavigate(operationalRouteByCode[code])}>{t("openLiveWorkspace")}</Button>}<Button onClick={()=>start()}>{t("newRecord")}</Button></div>}/>
  <div className="workspace-command-strip"><div><span className="command-kicker">{t("architectureDepth")}</span><strong>L3 {t("module")} → L4 {t("page")} → L5 {t("view")} → L6 {t("workspace")} → L7 {t("tab")} → L9 {t("section")}</strong></div><div className="workspace-state"><span className="state-dot live"></span>{t("operationalFoundation")}</div></div>
  <div className="workspace-tabs">{sections.map((s,i)=><button key={s} className={i===tab?"active":""} onClick={()=>{setTab(i);setLens("records")}}>{label(s)}</button>)}</div>
  <div className="workbench-lenses">{lenses.map(x=><button key={x.id} className={lens===x.id?"active":""} onClick={()=>setLens(x.id)}><span>{x.icon}</span><strong>{lensTitle(x)}</strong><small>{x.id==="records"?rows.length:rows.filter(r=>r.record_type===x.type).length}</small></button>)}</div>
  {error&&<div className="alert alert-error">{error}</div>}
  <div className="workspace-layout operational-layout"><section className="workspace-main panel"><div className="workspace-section-head"><div><span className="eyebrow">{code} / {String(tab+1).padStart(2,"0")}</span><h2>{label(section)}</h2><p>{lensTitle(current)}</p></div><Button onClick={()=>start(current.type)}>+ {t("newRecord")}</Button></div>
   <div className="workbench-toolbar"><div className="toolbar-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("search")}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{t("allStatuses")}</option>{statuses.map(s=><option key={s} value={s}>{statusText(s)}</option>)}</select><Button variant="secondary" onClick={load}>{loading?"…":"↻"}</Button></div>
   {loading&&!rows.length?<div className="workbench-loading">{t("loading")}</div>:!shown.length?<Empty title={t("noRecords")} description={t("noRecordsHelp")} action={<Button onClick={()=>start(current.type)}>+ {t("newRecord")}</Button>}/>:<div className="workbench-record-list">{shown.map(row=><article key={row.id} className="workbench-record"><div className="record-main"><div className="record-title-row"><strong>{row.title}</strong><Badge tone={statusTone(row.status) as any}>{statusText(row.status)}</Badge></div><p>{row.description||label(section)}</p><div className="record-meta"><span>{t("type")}: {label(String(row.record_type).replaceAll("_"," "))}</span><span>{t("owner")}: {row.owner_name||row.created_by_name||"—"}</span><span>{t("updated")}: {new Date(row.updated_at).toLocaleString(lang==="ku"?"ku-Arab":lang)}</span></div></div><div className="record-actions"><Button variant="secondary" onClick={()=>start(row.record_type,row)}>{t("edit")}</Button>{row.status!=="archived"&&<Button variant="ghost" onClick={()=>archive(row)}>{t("archived")}</Button>}</div></article>)}</div>}
  </section><aside className="workspace-aside"><section className="panel architecture-guardrail"><div className="panel-head"><h3>{t("completenessGate")}</h3><Badge tone="neutral">V6</Badge></div><div className="depth-chip-grid">{depth.map(x=><span key={x}>{label(x)}</span>)}</div></section><section className="panel mt"><div className="panel-head"><h3>{t("activity")}</h3><Badge tone="info">{activity.length}</Badge></div>{!activity.length?<p className="muted-text">{t("noData")}</p>:<div className="activity-list">{activity.slice(0,8).map(a=><div key={a.id}><span>{a.actor_name||a.actor_email||"System"}</span><strong>{label(String(a.action||"").replaceAll("_"," "))}</strong><small>{new Date(a.created_at).toLocaleString(lang==="ku"?"ku-Arab":lang)}</small></div>)}</div>}</section><section className="panel mt"><div className="panel-head"><h3>{t("implementationStatus")}</h3><Badge tone="good">{t("live")}</Badge></div><div className="status-stack"><div><span>{t("architecture")}</span><strong>{t("ready")}</strong></div><div><span>{t("records")}</span><strong>{t("live")}</strong></div><div><span>{t("workflow")}</span><strong>{t("live")}</strong></div><div><span>{t("permissions")}</span><strong>{t("partial")}</strong></div><div><span>{t("reports")}</span><strong>{t("partial")}</strong></div></div></section></aside></div>
  <Modal open={modal} onClose={()=>setModal(false)} title={editing?t("edit"):t("newRecord")} width={720}><form className="form-stack" onSubmit={save}><div className="form-grid"><Field label={t("recordTitle")}><input autoFocus required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label={t("recordType")}><select value={form.record_type} onChange={e=>setForm({...form,record_type:e.target.value})}>{lenses.map(x=><option key={x.type} value={x.type}>{lensTitle(x)}</option>)}</select></Field><Field label={t("recordStatus")}><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s} value={s}>{statusText(s)}</option>)}</select></Field><div></div><div className="span-2"><Field label={t("description")}><textarea rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div></div><p className="muted-text">{t("createRecordHelp")}</p><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setModal(false)}>{t("cancel")}</Button><Button type="submit">{t("save")}</Button></div></form></Modal>
 </div>;
}
