import React,{useEffect,useState} from "react";
import {api} from "../lib/api";
import {Button,Field} from "../components/ui";

export default function ProviderInvitePage({token,onDone}:{token:string,onDone:()=>void}){
 const [invite,setInvite]=useState<any>(null),[name,setName]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{api<any>(`/api/provider/invitations/validate?token=${encodeURIComponent(token)}`).then(r=>{setInvite(r.invitation);setName(r.invitation.name||"")}).catch(e=>setError(e.message))},[token]);
 async function accept(e:React.FormEvent){
  e.preventDefault();setError("");
  if(password.length<10)return setError("Password must be at least 10 characters.");
  if(password!==confirm)return setError("Passwords do not match.");
  setBusy(true);
  try{await api("/api/provider/invitations/accept",{method:"POST",body:JSON.stringify({token,name,password})});setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}
 }
 if(done)return <div className="auth-screen provider-invite-screen"><div className="auth-panel"><div className="auth-brand"><div className="brand-mark large">E</div><div><h1>Education Platform</h1><p>Provider Control Plane</p></div></div><div className="success-mark">✓</div><div className="auth-copy"><span className="eyebrow">ACCOUNT ACTIVATED</span><h2>Your provider account is ready</h2><p>You can now sign in with your email and the password you just created.</p></div><Button onClick={onDone}>Continue to sign in</Button></div><div className="auth-visual"><div className="visual-grid"></div><div className="visual-card v1"><strong>Provider Access</strong><span>Individual account · audited activity</span></div><div className="visual-card v2"><strong>Role Based</strong><span>Permissions follow approved responsibilities</span></div></div></div>;
 return <div className="auth-screen provider-invite-screen"><div className="auth-panel"><div className="auth-brand"><div className="brand-mark large">E</div><div><h1>Education Platform</h1><p>Provider Control Plane invitation</p></div></div><div className="auth-copy"><span className="eyebrow">PROVIDER TEAM INVITATION</span><h2>Activate your account</h2><p>{invite?`You were invited as ${invite.role_name}. Confirm your name and choose your own password.`:"Validating your private invitation…"}</p></div>{error&&<div className="alert alert-error">{error}</div>}{invite&&<form onSubmit={accept} className="form-stack"><Field label="Email"><input value={invite.email} disabled/></Field><Field label="Full name"><input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Provider role"><input value={invite.role_name} disabled/></Field><Field label="New password" hint="Minimum 10 characters"><input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></Field><Field label="Confirm password"><input type="password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></Field><Button disabled={busy}>{busy?"Activating…":"Activate provider account"}</Button><div className="auth-note">This invitation is private and time-limited. Your account activity will be recorded in the provider audit history.</div></form>}</div><div className="auth-visual"><div className="visual-grid"></div><div className="visual-card v1"><strong>Separate account</strong><span>No shared owner passwords</span></div><div className="visual-card v2"><strong>Least privilege</strong><span>Role + permission based access</span></div><div className="visual-card v3"><strong>Audited</strong><span>Provider actions remain attributable</span></div><div className="visual-orbit"></div></div></div>
}
