import React,{useEffect,useMemo,useState} from "react";
import {api} from "../lib/api";
import {Badge,Button,DataTable,Field,Modal,PageHeader} from "../components/ui";
import {useI18n} from "../lib/i18nContext";

type Role={code:string;name:string;description:string;permissions:string[]};
type Permission={code:string;group:string;name:string};
const makePassword=()=>`Edu-${crypto.randomUUID().slice(0,8)}!${Math.floor(Math.random()*90+10)}`;
const tone=(s:string)=>s==="active"||s==="accepted"?"good":s==="pending"?"warn":s==="suspended"||s==="revoked"||s==="expired"?"bad":"neutral";

export default function ProviderTeamPage(){
 const {lang,label}=useI18n();
 const c=(en:string,ku:string,ar:string,tr:string)=>lang==="ku"?ku:lang==="ar"?ar:lang==="tr"?tr:en;
 const [team,setTeam]=useState<any[]>([]),[invites,setInvites]=useState<any[]>([]),[roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[currentPermissions,setCurrentPermissions]=useState<string[]>([]),[currentUserId,setCurrentUserId]=useState("");
 const [tab,setTab]=useState<"team"|"invites"|"roles">("team"),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null);
 const [mode,setMode]=useState<"invite"|"direct">("invite"),[permissionMode,setPermissionMode]=useState<"role"|"custom">("role");
 const [form,setForm]=useState<any>({name:"",email:"",role_code:"provider_owner",preferred_language:"en",password:makePassword(),status:"active"});
 const [selected,setSelected]=useState<Set<string>>(new Set());
 const canManage=currentPermissions.includes("provider.team.manage")||currentPermissions.includes("provider.owner.manage"),canManageOwners=currentPermissions.includes("provider.owner.manage");
 const load=async()=>{const [t,r]=await Promise.all([api<any>("/api/provider/team"),api<any>("/api/provider/roles")]);setTeam(t.rows||[]);setInvites(t.invitations||[]);setCurrentPermissions(t.current_permissions||[]);setCurrentUserId(t.current_user_id||"");setRoles(r.roles||[]);setPermissions(r.permissions||[])};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const role=useMemo(()=>roles.find(r=>r.code===form.role_code),[roles,form.role_code]);
 useEffect(()=>{if(permissionMode==="role")setSelected(new Set(role?.permissions||[]))},[role?.code,permissionMode]);
 const grouped=useMemo(()=>Object.entries(permissions.reduce((a:Record<string,Permission[]>,p)=>{(a[p.group]??=[]).push(p);return a},{})),[permissions]);
 function computeOverrides(){if(permissionMode==="role")return {};const defaults=new Set(role?.permissions||[]),out:Record<string,"allow"|"deny">={};for(const p of permissions){const wanted=selected.has(p.code),base=defaults.has(p.code);if(wanted!==base)out[p.code]=wanted?"allow":"deny"}return out}
 function start(){setEdit(null);setError("");setResult(null);setMode("invite");setPermissionMode("role");setForm({name:"",email:"",role_code:"provider_owner",preferred_language:"en",password:makePassword(),status:"active"});setOpen(true)}
 function startEdit(row:any){const r=roles.find(x=>x.code===row.role_code),effective=new Set(r?.permissions||[]);for(const o of row.permission_overrides||[]){if(o.effect==="allow")effective.add(o.permission_code);else effective.delete(o.permission_code)}setEdit(row);setError("");setResult(null);setMode("direct");setForm({name:row.name,email:row.email,role_code:row.role_code,preferred_language:row.preferred_language||"en",password:"",status:row.status});setSelected(effective);setPermissionMode((row.permission_overrides||[]).length?"custom":"role");setOpen(true)}
 const toggle=(code:string)=>setSelected(s=>{const n=new Set(s);n.has(code)?n.delete(code):n.add(code);return n});
 async function submit(){setBusy(true);setError("");setResult(null);try{if(edit){await api(`/api/provider/team/users/${edit.id}`,{method:"PATCH",body:JSON.stringify({role_code:form.role_code,status:form.status,permission_overrides:computeOverrides()})});setOpen(false);await load();return}if(mode==="invite"){const r=await api<any>("/api/provider/team/invitations",{method:"POST",body:JSON.stringify({name:form.name,email:form.email,role_code:form.role_code,permission_overrides:computeOverrides()})});setResult({kind:"invite",url:r.invite_url,expires_at:r.expires_at,email:form.email});await load()}else{const r=await api<any>("/api/provider/team/users",{method:"POST",body:JSON.stringify({name:form.name,email:form.email,password:form.password,role_code:form.role_code,preferred_language:form.preferred_language,permission_overrides:computeOverrides()})});setResult({kind:"direct",url:r.login_url,email:form.email,password:form.password});await load()}}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function revoke(id:string){if(!confirm(c("Revoke this invitation?","ئەم بانگهێشتە هەڵبوەشێندرێتەوە؟","إلغاء هذه الدعوة؟","Bu davet iptal edilsin mi?")))return;try{await api(`/api/provider/team/invitations/${id}/revoke`,{method:"POST"});await load()}catch(e:any){setError(e.message)}}
 async function quickStatus(row:any,status:string){try{await api(`/api/provider/team/users/${row.id}`,{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e:any){setError(e.message)}}
 const copy=(v:string)=>navigator.clipboard?.writeText(v),roleOptions=roles.filter(r=>r.code!=="platform_owner"&&(canManageOwners||r.code!=="provider_owner"));
 return <div className="provider-team-page">
  <PageHeader title={c("Provider Team & Access","تیمی پلاتفۆرم و دەسەڵات","فريق المزوّد والصلاحيات","Sağlayıcı Ekibi ve Erişim")} description={c("P29 · Internal provider users, roles, permissions, invitations and segregation of duties.","P29 · بەکارهێنەرانی ناوخۆی پلاتفۆرم، ڕۆڵەکان، دەسەڵاتەکان، بانگهێشت و جیاکردنەوەی بەرپرسیارێتی.","P29 · مستخدمو المزوّد الداخليون والأدوار والصلاحيات والدعوات وفصل المهام.","P29 · Dahili sağlayıcı kullanıcıları, roller, yetkiler, davetler ve görev ayrılığı.")} actions={canManage?<Button onClick={start}>+ {c("Add provider user","زیادکردنی بەکارهێنەری پلاتفۆرم","إضافة مستخدم للمزوّد","Sağlayıcı kullanıcısı ekle")}</Button>:undefined}/>
  {error&&<div className="alert alert-error">{error}</div>}
  <div className="provider-team-hero"><div><span className="eyebrow">{c("PROVIDER CONTROL PLANE","بەشی کۆنترۆڵی پلاتفۆرم","لوحة تحكم المزوّد","SAĞLAYICI KONTROL DÜZLEMİ")}</span><h2>{c("One account per person. No shared owner passwords.","بۆ هەر کەسێک هەژمارێکی تایبەت؛ هیچ وشەی نهێنییەکی هاوبەش نییە.","حساب مستقل لكل شخص، بدون مشاركة كلمات مرور المالك.","Her kişi için ayrı hesap; ortak sahip parolası yok.")}</h2><p>{c("Add partners and employees with their own login, assign a standard role, then optionally customize specific permissions. Every change is recorded in provider audit.","هاوبەش و کارمەندەکان بە هەژماری تایبەتی خۆیان زیاد بکە، ڕۆڵێکی ستانداردیان پێ بدە و پاشان ئەگەر پێویست بوو دەسەڵاتی تایبەت ڕێکبخە. هەموو گۆڕانکارییەکان لە تۆماری پشکنینی پلاتفۆرم هەڵدەگیرێن.","أضف الشركاء والموظفين بحسابات مستقلة، وعيّن دوراً قياسياً ثم خصّص الصلاحيات عند الحاجة. تُسجل جميع التغييرات في سجل تدقيق المزوّد.","Ortakları ve çalışanları kendi hesaplarıyla ekleyin, standart rol atayın ve gerekirse belirli yetkileri özelleştirin. Tüm değişiklikler sağlayıcı denetiminde kaydedilir.")}</p></div><div className="provider-team-metrics"><div><span>{c("Active team","تیمی چالاک","الفريق النشط","Aktif ekip")}</span><strong>{team.filter(x=>x.status==="active").length}</strong></div><div><span>{c("Pending invites","بانگهێشتی چاوەڕوان","الدعوات المعلقة","Bekleyen davetler")}</span><strong>{invites.filter(x=>x.status==="pending").length}</strong></div><div><span>{c("Role templates","نموونەی ڕۆڵەکان","قوالب الأدوار","Rol şablonları")}</span><strong>{roles.filter(x=>x.code!=="platform_owner").length}</strong></div></div></div>
  <div className="workspace-tabs provider-tabs"><button className={tab==="team"?"active":""} onClick={()=>setTab("team")}>{c("Team","تیم","الفريق","Ekip")}</button><button className={tab==="invites"?"active":""} onClick={()=>setTab("invites")}>{c("Invitations","بانگهێشتەکان","الدعوات","Davetler")}</button><button className={tab==="roles"?"active":""} onClick={()=>setTab("roles")}>{c("Roles & Permissions","ڕۆڵ و دەسەڵاتەکان","الأدوار والصلاحيات","Roller ve Yetkiler")}</button></div>
  {tab==="team"&&<div className="panel"><DataTable rows={team} columns={[
    {key:"name",label:c("Provider user","بەکارهێنەری پلاتفۆرم","مستخدم المزوّد","Sağlayıcı kullanıcısı"),render:r=><div><strong>{r.name}</strong><small className="cell-sub">{r.email}{r.id===currentUserId?` · ${c("You","تۆ","أنت","Siz")}`:""}</small></div>},
    {key:"role_name",label:c("Role","ڕۆڵ","الدور","Rol"),render:r=><div><strong>{label(r.role_name)}</strong><small className="cell-sub">{r.role_code}</small></div>},
    {key:"status",label:c("Status","دۆخ","الحالة","Durum"),render:r=><Badge tone={tone(r.status) as any}>{label(r.status)}</Badge>},
    {key:"permission_overrides",label:c("Permissions","دەسەڵاتەکان","الصلاحيات","Yetkiler"),render:r=><span>{(r.permission_overrides||[]).length?`${r.permission_overrides.length} ${c("custom overrides","ڕێکخستنی تایبەت","تخصيصات","özel değişiklik")}`:c("Role defaults","دەسەڵاتی بنەڕەتی ڕۆڵ","صلاحيات الدور الافتراضية","Rol varsayılanları")}</span>},
    {key:"created_at",label:c("Added","زیادکراوە","أضيف","Eklendi"),render:r=>new Date(r.created_at).toLocaleDateString(lang==="ku"?"ku-Arab":lang)},
    {key:"actions",label:c("Actions","کردارەکان","الإجراءات","İşlemler"),render:r=><div className="row-actions"><Button variant="ghost" onClick={()=>startEdit(r)} disabled={!canManage}>{c("Edit","دەستکاری","تعديل","Düzenle")}</Button>{r.id!==currentUserId&&canManage&&(r.status==="active"?<Button variant="ghost" onClick={()=>quickStatus(r,"suspended")}>{c("Suspend","ڕاگرتن","تعليق","Askıya al")}</Button>:<Button variant="ghost" onClick={()=>quickStatus(r,"active")}>{c("Activate","چالاککردن","تفعيل","Etkinleştir")}</Button>)}</div>}
  ]}/></div>}
  {tab==="invites"&&<div className="panel"><DataTable rows={invites} empty={c("No provider invitations","هیچ بانگهێشتێکی پلاتفۆرم نییە","لا توجد دعوات للمزوّد","Sağlayıcı daveti yok")} columns={[
    {key:"name",label:c("Invitee","بانگهێشتکراو","المدعو","Davetli"),render:r=><div><strong>{r.name}</strong><small className="cell-sub">{r.email}</small></div>},{key:"role_code",label:c("Role","ڕۆڵ","الدور","Rol"),render:r=>label(roles.find(x=>x.code===r.role_code)?.name||r.role_code)},{key:"status",label:c("Status","دۆخ","الحالة","Durum"),render:r=><Badge tone={tone(r.status) as any}>{label(r.status)}</Badge>},{key:"expires_at",label:c("Expires","بەسەرچوون","ينتهي","Sona erer"),render:r=>new Date(r.expires_at).toLocaleString(lang==="ku"?"ku-Arab":lang)},{key:"created_by_name",label:c("Invited by","بانگهێشت لەلایەن","الدعوة بواسطة","Davet eden")},{key:"action",label:"",render:r=>r.status==="pending"&&canManage?<Button variant="ghost" onClick={()=>revoke(r.id)}>{c("Revoke","هەڵوەشاندنەوە","إلغاء","İptal et")}</Button>:"—"}
  ]}/></div>}
  {tab==="roles"&&<div className="role-catalog-grid">{roles.filter(r=>r.code!=="platform_owner").map(r=><section className="panel role-card" key={r.code}><div className="panel-head"><div><span className="nav-code">{r.code}</span><h3>{label(r.name)}</h3></div><Badge tone={r.code==="provider_owner"?"info":"neutral"}>{r.permissions.length} {c("permissions","دەسەڵات","صلاحية","yetki")}</Badge></div><p>{r.description}</p><div className="role-permission-list">{r.permissions.map(p=><span key={p}>{permissions.find(x=>x.code===p)?.name||p}</span>)}</div></section>)}</div>}

  <Modal open={open} onClose={()=>!busy&&setOpen(false)} title={edit?c("Edit provider access","دەستکاری دەسەڵاتی پلاتفۆرم","تعديل وصول المزوّد","Sağlayıcı erişimini düzenle"):c("Add provider user","زیادکردنی بەکارهێنەری پلاتفۆرم","إضافة مستخدم للمزوّد","Sağlayıcı kullanıcısı ekle")} width={920}>
   {result?<div className="provider-access-success"><div className="success-mark">✓</div><h3>{result.kind==="invite"?c("Invitation link is ready","لینکی بانگهێشت ئامادەیە","رابط الدعوة جاهز","Davet bağlantısı hazır"):c("Provider account is ready","هەژماری پلاتفۆرم ئامادەیە","حساب المزوّد جاهز","Sağlayıcı hesabı hazır")}</h3><p>{result.kind==="invite"?c("Send this private link to the person. They will choose their own password and activate the approved role.","ئەم لینکە تایبەتە بۆ کەسەکە بنێرە؛ خۆی وشەی نهێنی هەڵدەبژێرێت و ڕۆڵی پەسەندکراو چالاک دەکات.","أرسل الرابط الخاص للشخص ليختار كلمة مروره ويفعّل الدور المعتمد.","Bu özel bağlantıyı kişiye gönderin; kendi parolasını seçip onaylanan rolü etkinleştirsin."):c("Send the login details securely. The readable temporary password is shown only here.","زانیاری چوونەژوورەوە بە شێوەی پارێزراو بنێرە؛ وشەی نهێنی کاتی تەنها لێرە نیشان دەدرێت.","أرسل بيانات الدخول بشكل آمن؛ كلمة المرور المؤقتة تظهر هنا فقط.","Giriş bilgilerini güvenli şekilde gönderin; geçici parola yalnızca burada gösterilir.")}</p><div className="credential-card"><div><span>{result.kind==="invite"?c("Invitation URL","لینکی بانگهێشت","رابط الدعوة","Davet URL"):c("Login URL","لینکی چوونەژوورەوە","رابط الدخول","Giriş URL")}</span><strong>{result.url}</strong><button onClick={()=>copy(result.url)}>{c("Copy","کۆپی","نسخ","Kopyala")}</button></div><div><span>{c("Email","ئیمەیڵ","البريد الإلكتروني","E-posta")}</span><strong>{result.email}</strong><button onClick={()=>copy(result.email)}>{c("Copy","کۆپی","نسخ","Kopyala")}</button></div>{result.password&&<div><span>{c("Temporary password","وشەی نهێنی کاتی","كلمة المرور المؤقتة","Geçici parola")}</span><strong>{result.password}</strong><button onClick={()=>copy(result.password)}>{c("Copy","کۆپی","نسخ","Kopyala")}</button></div>}</div><div className="form-actions"><Button onClick={()=>setOpen(false)}>{c("Done","تەواو","تم","Bitti")}</Button></div></div>:<>
    {error&&<div className="alert alert-error">{error}</div>}
    {!edit&&<div className="account-mode-switch"><button className={mode==="invite"?"active":""} onClick={()=>setMode("invite")}><strong>{c("Invite link","لینکی بانگهێشت","رابط دعوة","Davet bağlantısı")}</strong><span>{c("Recommended · person sets own password","پێشنیارکراو · کەسەکە خۆی وشەی نهێنی دادەنێت","موصى به · الشخص يحدد كلمة مروره","Önerilen · kişi kendi parolasını belirler")}</span></button><button className={mode==="direct"?"active":""} onClick={()=>setMode("direct")}><strong>{c("Create account now","ئێستا هەژمار دروست بکە","إنشاء الحساب الآن","Hesabı şimdi oluştur")}</strong><span>{c("You set a temporary password","تۆ وشەی نهێنی کاتی دادەنێیت","أنت تحدد كلمة مرور مؤقتة","Geçici parolayı siz belirlersiniz")}</span></button></div>}
    <div className="form-grid mt"><Field label={c("Full name","ناوی تەواو","الاسم الكامل","Ad Soyad")}><input value={form.name} disabled={!!edit} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label={c("Email","ئیمەیڵ","البريد الإلكتروني","E-posta")}><input type="email" value={form.email} disabled={!!edit} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label={c("Provider role","ڕۆڵی پلاتفۆرم","دور المزوّد","Sağlayıcı rolü")}><select value={form.role_code} onChange={e=>{setForm({...form,role_code:e.target.value});setPermissionMode("role")}}>{roleOptions.map(r=><option key={r.code} value={r.code}>{label(r.name)}</option>)}</select></Field><Field label={c("Language","زمان","اللغة","Dil")}><select value={form.preferred_language} disabled={!!edit} onChange={e=>setForm({...form,preferred_language:e.target.value})}><option value="en">English</option><option value="ku">کوردی (سۆرانی)</option><option value="ar">العربية</option><option value="tr">Türkçe</option></select></Field>{edit&&<Field label={c("Account status","دۆخی هەژمار","حالة الحساب","Hesap durumu")}><select value={form.status} disabled={edit.id===currentUserId} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">{c("Active","چالاک","نشط","Aktif")}</option><option value="suspended">{c("Suspended","ڕاگیراو","معلق","Askıda")}</option><option value="disabled">{c("Disabled","ناچالاک","معطل","Devre dışı")}</option></select></Field>}{!edit&&mode==="direct"&&<Field label={c("Temporary password","وشەی نهێنی کاتی","كلمة المرور المؤقتة","Geçici parola")} hint={c("Minimum 10 characters","لانیکەم ١٠ پیت","10 أحرف على الأقل","En az 10 karakter")}><div className="input-action"><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setForm({...form,password:makePassword()})}>{c("Generate","دروستکردن","توليد","Üret")}</button></div></Field>}</div>
    <div className="permission-mode mt"><div><strong>{c("Permission model","شێوازی دەسەڵات","نموذج الصلاحيات","Yetki modeli")}</strong><span>{c("Start from the selected role template, or customize specific capabilities for this person.","لە نموونەی ڕۆڵی هەڵبژێردراو دەست پێ بکە، یان دەسەڵاتی تایبەت بۆ ئەم کەسە ڕێکبخە.","ابدأ من قالب الدور المحدد أو خصص صلاحيات محددة لهذا الشخص.","Seçilen rol şablonundan başlayın veya kişiye özel yetkileri düzenleyin.")}</span></div><div><button className={permissionMode==="role"?"active":""} onClick={()=>setPermissionMode("role")}>{c("Role defaults","بنەڕەتی ڕۆڵ","افتراضيات الدور","Rol varsayılanları")}</button><button className={permissionMode==="custom"?"active":""} onClick={()=>{setPermissionMode("custom");setSelected(new Set(role?.permissions||[]))}}>{c("Custom permissions","دەسەڵاتی تایبەت","صلاحيات مخصصة","Özel yetkiler")}</button></div></div>
    {permissionMode==="custom"&&<div className="permission-matrix">{grouped.map(([group,items])=><section key={group}><h4>{label(group)}</h4>{items.map(p=><label key={p.code}><input type="checkbox" checked={selected.has(p.code)} onChange={()=>toggle(p.code)} disabled={p.code==="provider.owner.manage"&&!canManageOwners}/><span><strong>{label(p.name)}</strong><small>{p.code}</small></span></label>)}</section>)}</div>}
    <div className="provider-sod-note"><strong>{c("Segregation of duties","جیاکردنەوەی بەرپرسیارێتی","فصل المهام","Görev ayrılığı")}</strong><span>{c("Only Provider Owners can grant owner authority. Suspended users lose all active sessions immediately.","تەنها خاوەنی پلاتفۆرم دەتوانێت دەسەڵاتی خاوەندارێتی بدات. بەکارهێنەری ڕاگیراو هەموو سێشنە چالاکەکانی دەستبەجێ دادەخرێن.","فقط مالكو المنصة يمكنهم منح صلاحية المالك. المستخدم المعلق تُلغى جلساته النشطة فوراً.","Yalnızca Sağlayıcı Sahipleri sahip yetkisi verebilir. Askıya alınan kullanıcının tüm aktif oturumları hemen kapatılır.")}</span></div>
    <div className="form-actions"><Button variant="secondary" onClick={()=>setOpen(false)} disabled={busy}>{c("Cancel","هەڵوەشاندنەوە","إلغاء","İptal")}</Button><Button onClick={submit} disabled={busy||(!edit&&(!form.name||!form.email))||(!edit&&mode==="direct"&&String(form.password).length<10)}>{busy?c("Saving…","پاشەکەوت دەکرێت…","جارٍ الحفظ…","Kaydediliyor…"):edit?c("Save access","پاشەکەوتکردنی دەسەڵات","حفظ الصلاحيات","Erişimi kaydet"):c("Create / invite user","دروستکردن / بانگهێشتکردن","إنشاء / دعوة المستخدم","Kullanıcı oluştur / davet et")}</Button></div>
   </>}
  </Modal>
 </div>
}
