import React,{useEffect,useState} from "react";
import {api,qs} from "../lib/api";
import {Badge,Button,PageHeader,StatCard} from "../components/ui";
import {useI18n} from "../lib/i18nContext";
import {moduleTitle} from "../data/moduleLocale";

export default function TenantDashboard({tenantId,branchId,tenant,onNavigate}:{tenantId:string,branchId:string|null,tenant:any,onNavigate?:(page:string)=>void}){
  const {lang,t}=useI18n();
  const [s,setS]=useState<any>({});
  const c=(en:string,ku:string,ar:string,tr:string)=>lang==="ku"?ku:lang==="ar"?ar:lang==="tr"?tr:en;
  useEffect(()=>{if(!tenantId)return;Promise.all([api<any>("/api/branches"+qs({tenant_id:tenantId})),api<any>("/api/students"+qs({tenant_id:tenantId,branch_id:branchId})),api<any>("/api/staff"+qs({tenant_id:tenantId,branch_id:branchId})),api<any>("/api/invoices"+qs({tenant_id:tenantId,branch_id:branchId}))]).then(([b,st,sf,inv])=>setS({branches:b.rows.length,students:st.rows.length,staff:sf.rows.length,invoices:inv.rows.length,outstanding:inv.rows.reduce((a:number,x:any)=>a+Math.max(0,Number(x.total)-Number(x.paid_total)),0)})).catch(()=>{})},[tenantId,branchId]);
  const launch=[
    ["B02",c("Applicant pipeline, offers and decisions","ڕەوتی داواکاران، پێشنیار و بڕیارەکان","مسار المتقدمين والعروض والقرارات","Aday süreci, teklifler ve kararlar")],["B05",c("Whole-student workspace and timeline","ژینگەی تەواوی قوتابی و مێژووی چالاکی","مساحة الطالب الشاملة والخط الزمني","Öğrencinin bütünsel çalışma alanı ve zaman çizelgesi")],["B01",c("Years, terms, grades and cohorts","ساڵ، وەرز، ئاست و کۆهۆرتەکان","السنوات والفصول والمراحل والمجموعات","Yıllar, dönemler, sınıflar ve kohortlar")],
    ["B07",c("Scheduling, rooms and constraints","خشتەبەندی، ژوور و سنوورەکان","الجدولة والقاعات والقيود","Planlama, odalar ve kısıtlar")],["B10",c("Registers, absences and interventions","تۆماری ئامادەبوون، غیاب و دەستێوەردان","السجلات والغياب والتدخلات","Yoklama, devamsızlık ve müdahaleler")],["B12",c("Teacher gradebooks and publishing","تۆماری نمرەی مامۆستا و بڵاوکردنەوە","دفاتر درجات المعلمين والنشر","Öğretmen not defterleri ve yayınlama")],
    ["B30",c("Student billing and family accounts","پسولەی قوتابی و هەژماری خێزان","فوترة الطلاب وحسابات الأسر","Öğrenci faturalama ve aile hesapları")],["B35",c("Staff lifecycle and workforce","خولی ژیانی کارمەند و هێزی کار","دورة حياة الموظفين والقوى العاملة","Personel yaşam döngüsü ve iş gücü")],["B16",c("Restricted case management","بەڕێوەبردنی کەیسی سنووردار و نهێنی","إدارة حالات مقيدة وسرية","Kısıtlı ve gizli vaka yönetimi")]
  ];
  return <div className="tenant-home">
    <PageHeader title={tenant?.name||c("School group workspace","ژینگەی کاری گرووپی قوتابخانە","مساحة عمل مجموعة المدارس","Okul grubu çalışma alanı")} description={branchId?c("Branch-scoped operational command center","ناوەندی کارپێکردن بۆ ئەم لقە","مركز عمليات ضمن نطاق الفرع","Şube kapsamlı operasyon merkezi"):c("A01 · Tenant / Customer Workspace · Group-level consolidated view","A01 · ژینگەی کاری کڕیار · دیمەنی یەکگرتووی ئاستی گرووپ","A01 · مساحة عمل العميل · عرض موحد على مستوى المجموعة","A01 · Müşteri çalışma alanı · Grup düzeyi birleşik görünüm")} actions={<><Badge tone="good">{branchId?c("Branch scope","ئاستی لق","نطاق الفرع","Şube kapsamı"):c("Group scope","ئاستی گرووپ","نطاق المجموعة","Grup kapsamı")}</Badge><Button variant="secondary" onClick={()=>onNavigate?.("module-A01")}>{c("Tenant settings","ڕێکخستنەکانی کڕیار","إعدادات العميل","Müşteri ayarları")}</Button></>}/>
    <div className="tenant-context-hero"><div><span className="eyebrow">{c("TENANT APPLICATION PLANE","بەشی کارکردنی کڕیار","تطبيق العميل","MÜŞTERİ UYGULAMASI")}</span><h2>{branchId?c("Local branch operations","کارپێکردنی لق","عمليات الفرع المحلي","Yerel şube operasyonları"):c("Education group command center","ناوەندی بەڕێوەبردنی گرووپی پەروەردە","مركز قيادة المجموعة التعليمية","Eğitim grubu komuta merkezi")}</h2><p>{c("Role-scoped access across organization, academics, people, finance, student care, workflows, reporting and administration.","دەستگەیشتن بە پێی ڕۆڵ بۆ ڕێکخراو، ئەکادیمی، کەسەکان، دارایی، چاودێری قوتابی، ڕەوتی کار، ڕاپۆرت و بەڕێوەبردن.","وصول حسب الدور إلى المؤسسة والأكاديميات والأفراد والمالية ورعاية الطلاب وسير العمل والتقارير والإدارة.","Organizasyon, akademik, kişiler, finans, öğrenci desteği, iş akışları, raporlama ve yönetim genelinde rol bazlı erişim.")}</p></div><div className="tenant-hero-meta"><span>{c("Plan","پلان","الخطة","Plan")} <strong>{tenant?.plan_code||"—"}</strong></span><span>{t("status")} <strong>{tenant?.status||"active"}</strong></span><span>{c("Currency","دراو","العملة","Para Birimi")} <strong>{tenant?.default_currency||"IQD"}</strong></span></div></div>
    <div className="stats-grid executive-stats mt">{!branchId&&<StatCard label={c("Branches / Campuses","لق / کامپەسەکان","الفروع / الحُرُم","Şubeler / Kampüsler")} value={s.branches??"—"} meta={c("Organization structure","پێکهاتەی ڕێکخراو","هيكل المؤسسة","Organizasyon yapısı")}/>}<StatCard label={t("students")} value={s.students??"—"} meta={c("Current scope","ئاستی ئێستا","النطاق الحالي","Mevcut kapsam")}/><StatCard label={c("Staff / Teachers","کارمەند / مامۆستا","الموظفون / المعلمون","Personel / Öğretmenler")} value={s.staff??"—"} meta={c("Current scope","ئاستی ئێستا","النطاق الحالي","Mevcut kapsam")}/><StatCard label={c("Invoices","پسولەکان","الفواتير","Faturalar")} value={s.invoices??"—"} meta={c("Student billing records","تۆمارەکانی پسولەی قوتابی","سجلات فوترة الطلاب","Öğrenci fatura kayıtları")}/><StatCard label={c("Outstanding","قەرزی ماوە","المستحق","Ödenmemiş")} value={Number(s.outstanding||0).toLocaleString()} meta={tenant?.default_currency||"IQD"}/></div>

    <div className="dashboard-composite mt"><section className="panel"><div className="panel-head"><div><span className="eyebrow">{c("SCHOOL OPERATING SYSTEM","سیستەمی کارپێکردنی قوتابخانە","نظام تشغيل المدرسة","OKUL İŞLETİM SİSTEMİ")}</span><h3>{c("Operational launchpad","ناوەندی دەستپێکردنی کار","منصة بدء العمليات","Operasyon başlangıç merkezi")}</h3></div><Badge tone="info">K-12</Badge></div><div className="launchpad-grid">{launch.map(([code,desc])=><button key={code} onClick={()=>onNavigate?.(`module-${code}`)}><span>{code}</span><strong>{moduleTitle(code,lang)}</strong><p>{desc}</p><i>→</i></button>)}</div></section>
      <section className="panel today-panel"><div className="panel-head"><div><span className="eyebrow">{c("TODAY","ئەمڕۆ","اليوم","BUGÜN")}</span><h3>{c("School operations","کارپێکردنی قوتابخانە","عمليات المدرسة","Okul operasyonları")}</h3></div><Badge tone="neutral">{c("Live foundation","بنەمای کارا","أساس فعال","Canlı temel")}</Badge></div><div className="today-list"><button onClick={()=>onNavigate?.("attendance")}><span>{t("attendance")}</span><strong>{c("Open daily register","کردنەوەی تۆماری ڕۆژانە","فتح سجل الحضور اليومي","Günlük yoklamayı aç")}</strong><i>→</i></button><button onClick={()=>onNavigate?.("students")}><span>{c("Student directory","بەڕێوەبردنی قوتابیان","دليل الطلاب","Öğrenci dizini")}</span><strong>{s.students??0} {c("in scope","لە ئاستی هەڵبژێردراودا","ضمن النطاق","kapsamda")}</strong><i>→</i></button><button onClick={()=>onNavigate?.("staff")}><span>{c("Staff directory","بەڕێوەبردنی کارمەندان","دليل الموظفين","Personel dizini")}</span><strong>{s.staff??0} {c("in scope","لە ئاستی هەڵبژێردراودا","ضمن النطاق","kapsamda")}</strong><i>→</i></button><button onClick={()=>onNavigate?.("finance")}><span>{t("finance")}</span><strong>{Number(s.outstanding||0).toLocaleString()} {tenant?.default_currency||"IQD"} {c("outstanding","ماوە","مستحق","ödenmemiş")}</strong><i>→</i></button></div></section></div>

    <div className="grid-3 mt"><section className="panel"><div className="panel-head"><h3>{c("Academic operations","کارپێکردنی ئەکادیمی","العمليات الأكاديمية","Akademik operasyonlar")}</h3><Badge tone="info">B01–B14</Badge></div><p className="muted-text">{c("Academic year, admissions, enrollment, curriculum, timetable, teaching, attendance, assessment, gradebook, exams and reporting.","ساڵی خوێندن، وەرگرتن، تۆمارکردن، پرۆگرامی خوێندن، خشتەی وانە، وانەوتنەوە، ئامادەبوون، هەڵسەنگاندن، نمرە، تاقیکردنەوە و ڕاپۆرت.","السنة الأكاديمية والقبول والتسجيل والمناهج والجداول والتدريس والحضور والتقييم والدرجات والاختبارات والتقارير.","Akademik yıl, kabul, kayıt, müfredat, ders programı, öğretim, devam, değerlendirme, notlar, sınavlar ve raporlama.")}</p><Button variant="ghost" onClick={()=>onNavigate?.("module-B01")}>{c("Explore academic core →","کردنەوەی بنەمای ئەکادیمی ←","استكشاف الأساس الأكاديمي ←","Akademik çekirdeği keşfet →")}</Button></section><section className="panel"><div className="panel-head"><h3>{c("Student care & community","چاودێری قوتابی و کۆمەڵگە","رعاية الطلاب والمجتمع","Öğrenci desteği ve topluluk")}</h3><Badge tone="info">B15–B29</Badge></div><p className="muted-text">{c("Behaviour, safeguarding, wellbeing, learning support, medical, portals, meetings, activities, trips, transport, pickup, meals and library.","هەڵسوکەوت، پاراستنی قوتابی، خۆشگوزەرانی، پشتگیری فێربوون، تەندروستی، پۆرتاڵەکان، کۆبوونەوە، چالاکی، گەشت، گواستنەوە، وەرگرتن، خواردن و کتێبخانە.","السلوك والحماية والرفاه ودعم التعلم والصحة والبوابات والاجتماعات والأنشطة والرحلات والنقل والاستلام والوجبات والمكتبة.","Davranış, koruma, iyi oluş, öğrenme desteği, sağlık, portallar, görüşmeler, etkinlikler, geziler, ulaşım, teslim alma, yemek ve kütüphane.")}</p><Button variant="ghost" onClick={()=>onNavigate?.("module-B16")}>{c("Explore student care →","کردنەوەی چاودێری قوتابی ←","استكشاف رعاية الطلاب ←","Öğrenci desteğini keşfet →")}</Button></section><section className="panel"><div className="panel-head"><h3>{c("Business & administration","کاروبار و بەڕێوەبردن","الأعمال والإدارة","İş ve yönetim")}</h3><Badge tone="info">B30–B56</Badge></div><p className="muted-text">{c("Billing, accounting, procurement, assets, facilities, HR, payroll, grants, finance, quality, IT, security, rollover and regulatory reporting.","پسولە، ژمێریاری، کڕین، سامان، بیناکان، HR، مووچە، گرەنت، دارایی، کوالێتی، IT، ئاسایش، گواستنەوەی ساڵ و ڕاپۆرتی یاسایی.","الفوترة والمحاسبة والمشتريات والأصول والمرافق والموارد البشرية والرواتب والمنح والمالية والجودة وتقنية المعلومات والأمن والترحيل والتقارير التنظيمية.","Faturalama, muhasebe, satın alma, varlıklar, tesisler, İK, bordro, hibeler, finans, kalite, BT, güvenlik, devir ve mevzuat raporlama.")}</p><Button variant="ghost" onClick={()=>onNavigate?.("module-B30")}>{c("Explore operations →","کردنەوەی کارپێکردن ←","استكشاف العمليات ←","Operasyonları keşfet →")}</Button></section></div>
  </div>
}
